<a href="https://colab.research.google.com/github/syq-tju/TensorFlowCrash/blob/main/TensorFlow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!apt install -y git


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.


In [7]:
!git clone https://github.com/syq-tju/TensorFlowCrash.git

Cloning into 'TensorFlowCrash'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.


In [8]:
!git config --global user.email "shiyuqi@tju.edu.cn"
!git config --global user.name "syq-tju"

### 1.3.1 导入TensorFlow

In [9]:
import tensorflow as tf
print("Tensorflow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
#print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version: 2.14.0
Eager execution is: True


### 1.3.2 TensorFlow编码风格

### 1.3.3 动态图机制（Eager Execution）

In [10]:

#var = tf.Variable([3,3])
with tf.device('/GPU:0'):
    var = tf.Variable([3,3])


# 列出所有的 GPU 设备
gpus = tf.config.list_physical_devices('GPU')

# 如果有 GPU 设备
if gpus:
    print('Running on GPU')
    for gpu in gpus:
        print("Device name:", gpu.name)

    # 检查 var 变量是否被分配给了第一个 GPU 设备
    print('Is var on GPU #0?', var.device.endswith('GPU:0'))
else:
    print('No GPU devices found.')


print("Device for var:", var.device)


No GPU devices found.
Device for var: /job:localhost/replica:0/task:0/device:CPU:0


### 1.3.4 声明Eager变量

In [11]:
t0 = 24
t1 = tf.Variable(24)
t2 = tf.Variable([[[0.,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
t0,t1,t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [12]:
f64 = tf.Variable(89,dtype = tf.float64)
f64.dtype

tf.float64

In [13]:
f1 = tf.Variable(89.)
f1
f1.assign(98)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

### 1.3.5 声明TensorFlow常量

In [14]:
m_o_1 = tf.constant(42)
m_o_1
#m_o_1.numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [15]:
unit = tf.constant(1,dtype = tf.int64)
unit
#unit.numpy()

<tf.Tensor: shape=(), dtype=int64, numpy=1>

### 1.3.6 创建tensor张量

In [16]:
t2 = tf.Variable([[[0.,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(t2.shape)
r1 = tf.reshape(t2,[2,6])
r2 = tf.reshape(t2,[1,-1])
t2,r1,r2

(2, 2, 3)


(<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 6), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 12), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
       dtype=float32)>)

### 1.3.7 张量的秩（张量的维数）

In [17]:
tf.rank(t2)   #表述t2是三维的张量，需要三个量确定t2里面的任意元素位置。

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### 1.3.8 指定张量的元素

In [18]:
t3 = t2[1,0,2]
t3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

### 1.3.9 张量转化为Numpy/Python变量

In [19]:
print(t2.numpy())
print(t2[1,0,2].numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
8.0


### 1.3.10 计算张量的大小

In [20]:
s = tf.size(input = t2).numpy()
s

12

### 1.3.11 查看张量的数据类型

In [21]:
t3.dtype

tf.float32

### 1.3.12 张量元素的基本运算规则

In [22]:
t2 * t2

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

### 1.3.13 广播机制

In [23]:
t4 = t2 * 4
print(t4)
t5 = tf.broadcast_to(t3,[2,2,3])
print(t5)


tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[[8. 8. 8.]
  [8. 8. 8.]]

 [[8. 8. 8.]
  [8. 8. 8.]]], shape=(2, 2, 3), dtype=float32)


### 1.3.14 TensorFlow 转置和矩阵乘法


In [24]:
u = tf.constant([[3,4,3]])
v = tf.constant([[1,2,3]])
tf.matmul(u,tf.transpose(v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[20]], dtype=int32)>

### 1.3.15 张量数据类型转化

In [25]:
i = tf.cast(t1,dtype=tf.int32)
print(i)
j = tf.cast(tf.constant(2.5),dtype=tf.int32)
print(j)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>
tf.Tensor(2, shape=(), dtype=int32)


### 1.3.16 声明不规则张量

In [26]:
ragged = tf.ragged.constant([[1,2,3,4],[],[5,6,7],[8],[9,10]])
print(ragged)
print(ragged.shape)
print(ragged.dtype)
print(ragged.to_tensor())


<tf.RaggedTensor [[1, 2, 3, 4], [], [5, 6, 7], [8], [9, 10]]>
(5, None)
<dtype: 'int32'>
tf.Tensor(
[[ 1  2  3  4]
 [ 0  0  0  0]
 [ 5  6  7  0]
 [ 8  0  0  0]
 [ 9 10  0  0]], shape=(5, 4), dtype=int32)


## 1.4 TensorFlow的基础操作

In [27]:
from numpy import s_
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[7,8,9],[10,11,12]])
s_add = x + y
s_sub = x - y
s_mul = x * y
s_div = x / y
s_add,s_sub,s_mul,s_div

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 8, 10, 12],
        [14, 16, 18]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[-6, -6, -6],
        [-6, -6, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7, 16, 27],
        [40, 55, 72]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]])>)

### 1.4.1 计算平方差

In [28]:
s = tf.square(x - y)
s

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[36, 36, 36],
       [36, 36, 36]], dtype=int32)>

In [29]:
#tf.reduce_mean()
#tf.reduce_sum()
numbers = tf.constant([[4.,5.],[7.,3.]])
#计算全体压缩值
tf.reduce_mean(numbers)
tf.reduce_sum(numbers)
#跨列的平均值，跨行的平均值
tf.reduce_mean(numbers,axis=0),tf.reduce_mean(numbers,axis=1)
#保留轴的被压缩的长度（1）
tf.reduce_mean(numbers,axis=0,keepdims=True),tf.reduce_mean(numbers,axis=1,keepdims=True)

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[4.5],
        [5. ]], dtype=float32)>)

### 1.4.3 随机初始化张量

In [30]:
#tf.random.normal(shape,mean=0,stddev=1,dtype=tf.float32)
tf.random.normal(shape=[2,3])
#tf.random.uniform(shape,minval=0,maxval=None,dtype=float32,seed=None,name=None)
tf.random.uniform(shape=[2,3])


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.3058046 , 0.10020697, 0.65838623],
       [0.7253113 , 0.66763663, 0.39767575]], dtype=float32)>

### 1.4.4 查找最大值和最小值元素的索引

In [31]:
#tf.argmax(input,axis=None,name=None,output_type=tf.int64)
#tf.argmin(input,axis=None,name=None,output_type=tf.int64)
t5 = tf.constant([1,2,3,4,5,6,7,8,9])
print(t5)
i = tf.argmax(input=t5)
print("index of max is: ",i.numpy())
print("Max element is: ",t5[i].numpy())

t6 = tf.reshape(t5,[3,3])
print(t6)
i = tf.argmax(t6,axis=0)
print("index of max down rows: ",i.numpy())


tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
index of max is:  8
Max element is:  9
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
index of max down rows:  [2 2 2]


### 1.4.5 使用checkpoint恢复张量

In [32]:
variable = tf.Variable([[1,2,3,4],[5,6,7,8]])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('/vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>


In [33]:
!git add .
!git commit -m "Add Chapter 1"


hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> TensorFlowCrash
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached TensorFlowCrash
hint: 
hint: See "git help submodule" for more information.
[main f1c2481] Add Chapter 1
 1 file changed, 1 insertion(+)
 create mode 160000 TensorFlowCrash


In [35]:
!git push origin master


error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/syq-tju/TensorFlowCrash.git'
